# .github/.actionlint.yaml
self-hosted-runner:
  labels: []

ignore: ['expression']   # Ignore all "property ... not defined in object type {}" errors
# Or more targeted (if you want to keep other expression checks):
# ignore:
#   - 'property "summary" is not defined'
#   - 'property "validation" is not defined'
